-- Chat examples
target("chat_create_chat_completion", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_chat_completion.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("chat_create_chat_completion_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_chat_completion_async.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("chat_ongoing_user_convo", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/ongoing_user_convo.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

-- Chat conversation examples
target("chat_conversation_adduserdata", function()
    set_kind("binary")
    set_default(false)
    add_files("conversation/examples/adduserdata.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("chat_conversation_getjsonobject", function()
    set_kind("binary")
    set_default(false)
    add_files("conversation/examples/getjsonobject.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("chat_conversation_getlastresponse", function()
    set_kind("binary")
    set_default(false)
    add_files("conversation/examples/getlastresponse.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("chat_conversation_getrawconversation", function()
    set_kind("binary")
    set_default(false)
    add_files("conversation/examples/getrawconversation.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("chat_conversation_poplastresponse", function()
    set_kind("binary")
    set_default(false)
    add_files("conversation/examples/poplastresponse.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("chat_conversation_popsystemdata", function()
    set_kind("binary")
    set_default(false)
    add_files("conversation/examples/popsystemdata.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("chat_conversation_popuserdata", function()
    set_kind("binary")
    set_default(false)
    add_files("conversation/examples/popuserdata.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("chat_conversation_setsystemdata", function()
    set_kind("binary")
    set_default(false)
    add_files("conversation/examples/setsystemdata.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("chat_conversation_update", function()
    set_kind("binary")
    set_default(false)
    add_files("conversation/examples/update.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)
