target("fine_tunes_cancel_fine_tune", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/cancel_fine_tune.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("fine_tunes_cancel_fine_tune_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/cancel_fine_tune_async.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("fine_tunes_create_fine_tune", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_fine_tune.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("fine_tunes_create_fine_tune_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_fine_tune_async.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("fine_tunes_delete_fine_tune_model", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/delete_fine_tune_model.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("fine_tunes_delete_fine_tune_model_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/delete_fine_tune_model_async.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("fine_tunes_list_fine_tune_events", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/list_fine_tune_events.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("fine_tunes_list_fine_tune_events_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/list_fine_tune_events_async.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("fine_tunes_list_fine_tunes", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/list_fine_tunes.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("fine_tunes_list_fine_tunes_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/list_fine_tunes_async.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("fine_tunes_retrieve_fine_tune", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/retrieve_fine_tune.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("fine_tunes_retrieve_fine_tune_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/retrieve_fine_tune_async.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)
