target("embeddings_create_embedding", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_embedding.cpp")
    add_includedirs("../../liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("embeddings_create_embedding_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_embedding_async.cpp")
    add_includedirs("../../liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)
