-- Project setup
set_project("liboai")
set_version("4.0.1")
set_languages("c++17")

-- Dependencies
add_requires("nlohmann_json", "libcurl")

-- Main library target
target("oai")
    set_kind("static")
    -- Components (11 files)
    add_files(
        "liboai/components/audio.cpp",
        "liboai/components/azure.cpp",
        "liboai/components/chat.cpp",
        "liboai/components/completions.cpp",
        "liboai/components/edits.cpp",
        "liboai/components/embeddings.cpp",
        "liboai/components/files.cpp",
        "liboai/components/fine_tunes.cpp",
        "liboai/components/images.cpp",
        "liboai/components/models.cpp",
        "liboai/components/moderations.cpp",
        -- Core (3 files)
        "liboai/core/authorization.cpp",
        "liboai/core/netimpl.cpp",
        "liboai/core/response.cpp"
    )
    add_includedirs("liboai/include", {public = true})
    add_packages("nlohmann_json", "libcurl")

-- Audio examples (6)
target("audio_create_speech")
    set_kind("binary")
    set_default(false)
    add_files("documentation/audio/examples/create_speech.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("audio_create_speech_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/audio/examples/create_speech_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("audio_create_transcription")
    set_kind("binary")
    set_default(false)
    add_files("documentation/audio/examples/create_transcription.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("audio_create_transcription_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/audio/examples/create_transcription_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("audio_create_translation")
    set_kind("binary")
    set_default(false)
    add_files("documentation/audio/examples/create_translation.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("audio_create_translation_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/audio/examples/create_translation_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

-- Authorization examples (11)
target("authorization_set_azure_key")
    set_kind("binary")
    set_default(false)
    add_files("documentation/authorization/examples/set_azure_key.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("authorization_set_azure_key_env")
    set_kind("binary")
    set_default(false)
    add_files("documentation/authorization/examples/set_azure_key_env.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("authorization_set_azure_key_file")
    set_kind("binary")
    set_default(false)
    add_files("documentation/authorization/examples/set_azure_key_file.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("authorization_set_key")
    set_kind("binary")
    set_default(false)
    add_files("documentation/authorization/examples/set_key.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("authorization_set_key_env_var")
    set_kind("binary")
    set_default(false)
    add_files("documentation/authorization/examples/set_key_env_var.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("authorization_set_key_file")
    set_kind("binary")
    set_default(false)
    add_files("documentation/authorization/examples/set_key_file.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("authorization_set_organization")
    set_kind("binary")
    set_default(false)
    add_files("documentation/authorization/examples/set_organization.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("authorization_set_organization_env_var")
    set_kind("binary")
    set_default(false)
    add_files("documentation/authorization/examples/set_organization_env_var.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("authorization_set_organization_file")
    set_kind("binary")
    set_default(false)
    add_files("documentation/authorization/examples/set_organization_file.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("authorization_set_proxies")
    set_kind("binary")
    set_default(false)
    add_files("documentation/authorization/examples/set_proxies.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("authorization_set_proxy_auth")
    set_kind("binary")
    set_default(false)
    add_files("documentation/authorization/examples/set_proxy_auth.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

-- Azure examples (12)
target("azure_create_chat_completion")
    set_kind("binary")
    set_default(false)
    add_files("documentation/azure/examples/create_chat_completion.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("azure_create_chat_completion_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/azure/examples/create_chat_completion_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("azure_create_completion")
    set_kind("binary")
    set_default(false)
    add_files("documentation/azure/examples/create_completion.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("azure_create_completion_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/azure/examples/create_completion_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("azure_create_embedding")
    set_kind("binary")
    set_default(false)
    add_files("documentation/azure/examples/create_embedding.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("azure_create_embedding_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/azure/examples/create_embedding_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("azure_delete_generated_image")
    set_kind("binary")
    set_default(false)
    add_files("documentation/azure/examples/delete_generated_image.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("azure_delete_generated_image_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/azure/examples/delete_generated_image_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("azure_get_generated_image")
    set_kind("binary")
    set_default(false)
    add_files("documentation/azure/examples/get_generated_image.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("azure_get_generated_image_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/azure/examples/get_generated_image_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("azure_request_image_generation")
    set_kind("binary")
    set_default(false)
    add_files("documentation/azure/examples/request_image_generation.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("azure_request_image_generation_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/azure/examples/request_image_generation_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

-- Chat examples (3)
target("chat_create_chat_completion")
    set_kind("binary")
    set_default(false)
    add_files("documentation/chat/examples/create_chat_completion.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("chat_create_chat_completion_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/chat/examples/create_chat_completion_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("chat_ongoing_user_convo")
    set_kind("binary")
    set_default(false)
    add_files("documentation/chat/examples/ongoing_user_convo.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

-- Chat conversation examples (9)
target("chat_conversation_adduserdata")
    set_kind("binary")
    set_default(false)
    add_files("documentation/chat/conversation/examples/adduserdata.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("chat_conversation_getjsonobject")
    set_kind("binary")
    set_default(false)
    add_files("documentation/chat/conversation/examples/getjsonobject.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("chat_conversation_getlastresponse")
    set_kind("binary")
    set_default(false)
    add_files("documentation/chat/conversation/examples/getlastresponse.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("chat_conversation_getrawconversation")
    set_kind("binary")
    set_default(false)
    add_files("documentation/chat/conversation/examples/getrawconversation.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("chat_conversation_poplastresponse")
    set_kind("binary")
    set_default(false)
    add_files("documentation/chat/conversation/examples/poplastresponse.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("chat_conversation_popsystemdata")
    set_kind("binary")
    set_default(false)
    add_files("documentation/chat/conversation/examples/popsystemdata.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("chat_conversation_popuserdata")
    set_kind("binary")
    set_default(false)
    add_files("documentation/chat/conversation/examples/popuserdata.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("chat_conversation_setsystemdata")
    set_kind("binary")
    set_default(false)
    add_files("documentation/chat/conversation/examples/setsystemdata.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("chat_conversation_update")
    set_kind("binary")
    set_default(false)
    add_files("documentation/chat/conversation/examples/update.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

-- Completions examples (2)
target("completions_generate_completion")
    set_kind("binary")
    set_default(false)
    add_files("documentation/completions/examples/generate_completion.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("completions_generate_completion_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/completions/examples/generate_completion_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

-- Edits examples (2)
target("edits_create_edit")
    set_kind("binary")
    set_default(false)
    add_files("documentation/edits/examples/create_edit.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("edits_create_edit_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/edits/examples/create_edit_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

-- Embeddings examples (2)
target("embeddings_create_embedding")
    set_kind("binary")
    set_default(false)
    add_files("documentation/embeddings/examples/create_embedding.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("embeddings_create_embedding_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/embeddings/examples/create_embedding_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

-- Files examples (10)
target("files_delete_file")
    set_kind("binary")
    set_default(false)
    add_files("documentation/files/examples/delete_file.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("files_delete_file_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/files/examples/delete_file_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("files_download_uploaded_file")
    set_kind("binary")
    set_default(false)
    add_files("documentation/files/examples/download_uploaded_file.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("files_download_uploaded_file_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/files/examples/download_uploaded_file_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("files_list_files")
    set_kind("binary")
    set_default(false)
    add_files("documentation/files/examples/list_files.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("files_list_files_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/files/examples/list_files_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("files_retrieve_file")
    set_kind("binary")
    set_default(false)
    add_files("documentation/files/examples/retrieve_file.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("files_retrieve_file_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/files/examples/retrieve_file_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("files_upload_file")
    set_kind("binary")
    set_default(false)
    add_files("documentation/files/examples/upload_file.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("files_upload_file_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/files/examples/upload_file_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

-- Fine-tunes examples (12)
target("fine_tunes_cancel_fine_tune")
    set_kind("binary")
    set_default(false)
    add_files("documentation/fine-tunes/examples/cancel_fine_tune.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("fine_tunes_cancel_fine_tune_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/fine-tunes/examples/cancel_fine_tune_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("fine_tunes_create_fine_tune")
    set_kind("binary")
    set_default(false)
    add_files("documentation/fine-tunes/examples/create_fine_tune.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("fine_tunes_create_fine_tune_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/fine-tunes/examples/create_fine_tune_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("fine_tunes_delete_fine_tune_model")
    set_kind("binary")
    set_default(false)
    add_files("documentation/fine-tunes/examples/delete_fine_tune_model.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("fine_tunes_delete_fine_tune_model_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/fine-tunes/examples/delete_fine_tune_model_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("fine_tunes_list_fine_tune_events")
    set_kind("binary")
    set_default(false)
    add_files("documentation/fine-tunes/examples/list_fine_tune_events.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("fine_tunes_list_fine_tune_events_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/fine-tunes/examples/list_fine_tune_events_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("fine_tunes_list_fine_tunes")
    set_kind("binary")
    set_default(false)
    add_files("documentation/fine-tunes/examples/list_fine_tunes.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("fine_tunes_list_fine_tunes_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/fine-tunes/examples/list_fine_tunes_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("fine_tunes_retrieve_fine_tune")
    set_kind("binary")
    set_default(false)
    add_files("documentation/fine-tunes/examples/retrieve_fine_tune.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("fine_tunes_retrieve_fine_tune_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/fine-tunes/examples/retrieve_fine_tune_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

-- Images examples (7)
target("images_download_generated_image")
    set_kind("binary")
    set_default(false)
    add_files("documentation/images/examples/download_generated_image.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("images_generate_edit")
    set_kind("binary")
    set_default(false)
    add_files("documentation/images/examples/generate_edit.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("images_generate_edit_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/images/examples/generate_edit_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("images_generate_image")
    set_kind("binary")
    set_default(false)
    add_files("documentation/images/examples/generate_image.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("images_generate_image_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/images/examples/generate_image_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("images_generate_variation")
    set_kind("binary")
    set_default(false)
    add_files("documentation/images/examples/generate_variation.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("images_generate_variation_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/images/examples/generate_variation_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

-- Models examples (4)
target("models_list_models")
    set_kind("binary")
    set_default(false)
    add_files("documentation/models/examples/list_models.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("models_list_models_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/models/examples/list_models_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("models_retrieve_model")
    set_kind("binary")
    set_default(false)
    add_files("documentation/models/examples/retrieve_model.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("models_retrieve_model_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/models/examples/retrieve_model_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

-- Moderations examples (2)
target("moderations_create_moderation")
    set_kind("binary")
    set_default(false)
    add_files("documentation/moderations/examples/create_moderation.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")

target("moderations_create_moderation_async")
    set_kind("binary")
    set_default(false)
    add_files("documentation/moderations/examples/create_moderation_async.cpp")
    add_includedirs("liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
