target("audio_create_speech", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_speech.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("audio_create_speech_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_speech_async.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("audio_create_transcription", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_transcription.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("audio_create_transcription_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_transcription_async.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("audio_create_translation", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_translation.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("audio_create_translation_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_translation_async.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)
