target("azure_create_chat_completion", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/create_chat_completion.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("azure_create_chat_completion_async", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/create_chat_completion_async.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("azure_create_completion", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/create_completion.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("azure_create_completion_async", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/create_completion_async.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("azure_create_embedding", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/create_embedding.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("azure_create_embedding_async", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/create_embedding_async.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("azure_delete_generated_image", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/delete_generated_image.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("azure_delete_generated_image_async", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/delete_generated_image_async.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("azure_get_generated_image", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/get_generated_image.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("azure_get_generated_image_async", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/get_generated_image_async.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("azure_request_image_generation", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/request_image_generation.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("azure_request_image_generation_async", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/request_image_generation_async.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)
