target("moderations_create_moderation", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_moderation.cpp")
    add_includedirs("../../liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("moderations_create_moderation_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_moderation_async.cpp")
    add_includedirs("../../liboai/include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)
