target("edits_create_edit", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_edit.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("edits_create_edit_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/create_edit_async.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)
