target("images_download_generated_image", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/download_generated_image.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("images_generate_edit", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/generate_edit.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("images_generate_edit_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/generate_edit_async.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("images_generate_image", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/generate_image.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("images_generate_image_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/generate_image_async.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("images_generate_variation", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/generate_variation.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("images_generate_variation_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/generate_variation_async.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)
