target("images_download_generated_image", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/download_generated_image.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("images_generate_edit", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/generate_edit.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("images_generate_edit_async", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/generate_edit_async.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("images_generate_image", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/generate_image.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("images_generate_image_async", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/generate_image_async.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("images_generate_variation", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/generate_variation.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)

target("images_generate_variation_async", function()
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_toolchains("clang")
    set_policy("build.c++.modules", true)
    set_policy("build.c++.modules.reuse", true)
    add_files("examples/generate_variation_async.cpp")
    add_packages("nlohmann_json", "cpr")
    add_deps("oai")
end)
