target("completions_generate_completion", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/generate_completion.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)

target("completions_generate_completion_async", function()
    set_kind("binary")
    set_default(false)
    add_files("examples/generate_completion_async.cpp")
    add_includedirs("../../include")
    add_packages("nlohmann_json", "libcurl")
    add_deps("oai")
end)
